// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

export const supabaseConfigError = !SUPABASE_PUBLISHABLE_KEY?.trim()
  ? "[FitBlock] Chave Supabase em falta no build. Defina VITE_SUPABASE_PUBLISHABLE_KEY ou SUPABASE_ANON_KEY e reinicie o deploy/dev server."
  : !SUPABASE_URL?.trim()
    ? "[FitBlock] URL Supabase em falta. Defina VITE_SUPABASE_URL (ex: https://xxxx.supabase.co) e reinicie o deploy/dev server."
    : null;

const resolvedSupabaseUrl = SUPABASE_URL?.trim() || "https://invalid.local";
const resolvedSupabasePublishableKey = SUPABASE_PUBLISHABLE_KEY?.trim() || "missing-supabase-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(resolvedSupabaseUrl, resolvedSupabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
